; auto-generated by lazyc
extern lazyc_argc
extern lazyc_argv
extern lazyc_sys_read
extern lazyc_sys_write
extern lazyc_sys_open
extern lazyc_sys_close
extern lazyc_sys_stat
extern lazyc_sys_mmap
extern lazyc_sys_munmap
extern lazyc_sys_exit
section .text
global lazyc_exit
lazyc_exit:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov qword [rbp-8], rdi
    mov rax, [rbp-8]
    push rax
    pop rdi
    call lazyc_sys_exit
    push rax
    add rsp, 8
    mov rax, 0
    push rax
    pop rax
    leave
    ret
    xor rax, rax
    leave
    ret
global lazyc_alloc
lazyc_alloc:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov qword [rbp-8], rdi
    mov rax, [rbp-8]
    push rax
    mov rax, 8
    push rax
    pop rcx
    pop rax
    add rax, rcx
    push rax
    mov rax, 4095
    push rax
    pop rcx
    pop rax
    add rax, rcx
    push rax
    pop rax
    mov qword [rbp-16], rax
    mov rax, [rbp-16]
    push rax
    mov rax, [rbp-16]
    push rax
    mov rax, [rbp-16]
    push rax
    mov rax, 4096
    push rax
    pop rcx
    pop rax
    cqo
    idiv rcx
    push rax
    mov rax, 4096
    push rax
    pop rcx
    pop rax
    imul rax, rcx
    push rax
    pop rcx
    pop rax
    sub rax, rcx
    push rax
    pop rcx
    pop rax
    sub rax, rcx
    push rax
    pop rax
    mov qword [rbp-16], rax
    xor rax, rax
    push rax
    pop rax
    push rax
    mov rax, [rbp-16]
    push rax
    mov rax, 3
    push rax
    mov rax, 34
    push rax
    mov rax, -1
    push rax
    mov rax, 0
    push rax
    pop r9
    pop r8
    pop rcx
    pop rdx
    pop rsi
    pop rdi
    call lazyc_sys_mmap
    push rax
    pop rax
    mov qword [rbp-24], rax
    mov rax, [rbp-24]
    push rax
    pop rax
    push rax
    pop rax
    mov qword [rbp-32], rax
    mov rax, [rbp-32]
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    setl al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L0
    mov rax, [rbp-32]
    push rax
    mov rax, -4096
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    setg al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L1
    xor rax, rax
    push rax
    pop rax
    push rax
    pop rax
    leave
    ret
.L1:
.L0:
    mov rax, [rbp-24]
    push rax
    pop rax
    push rax
    pop rax
    mov qword [rbp-40], rax
    mov rax, [rbp-40]
    push rax
    mov rax, [rbp-16]
    push rax
    pop rax
    pop rcx
    mov qword [rcx], rax
    mov rax, [rbp-24]
    push rax
    mov rax, 8
    push rax
    pop rcx
    pop rax
    add rax, rcx
    push rax
    pop rax
    leave
    ret
    xor rax, rax
    leave
    ret
global lazyc_free
lazyc_free:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov qword [rbp-8], rdi
    mov rax, [rbp-8]
    push rax
    xor rax, rax
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    sete al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L2
    mov rax, 0
    push rax
    pop rax
    leave
    ret
.L2:
    mov rax, [rbp-8]
    push rax
    mov rax, 8
    push rax
    pop rcx
    pop rax
    sub rax, rcx
    push rax
    pop rax
    mov qword [rbp-16], rax
    mov rax, [rbp-16]
    push rax
    pop rax
    push rax
    pop rax
    mov qword [rbp-24], rax
    mov rax, [rbp-24]
    push rax
    pop rax
    mov rax, [rax]
    push rax
    pop rax
    mov qword [rbp-32], rax
    mov rax, [rbp-16]
    push rax
    mov rax, [rbp-32]
    push rax
    pop rsi
    pop rdi
    call lazyc_sys_munmap
    push rax
    pop rax
    mov qword [rbp-40], rax
    mov rax, [rbp-40]
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    setne al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L3
    mov rax, 0
    push rax
    pop rax
    leave
    ret
.L3:
    mov rax, 1
    push rax
    pop rax
    leave
    ret
    xor rax, rax
    leave
    ret
global lazyc_write_bytes
lazyc_write_bytes:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    mov qword [rbp-8], rdi
    mov qword [rbp-16], rsi
    mov rax, 0
    push rax
    pop rax
    mov qword [rbp-24], rax
.L4:
    mov rax, [rbp-24]
    push rax
    mov rax, [rbp-16]
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    setl al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L5
    mov rax, 1
    push rax
    mov rax, [rbp-8]
    push rax
    mov rax, [rbp-24]
    push rax
    pop rcx
    pop rax
    add rax, rcx
    push rax
    mov rax, [rbp-16]
    push rax
    mov rax, [rbp-24]
    push rax
    pop rcx
    pop rax
    sub rax, rcx
    push rax
    pop rdx
    pop rsi
    pop rdi
    call lazyc_sys_write
    push rax
    pop rax
    mov qword [rbp-32], rax
    mov rax, [rbp-32]
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    setle al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L6
    mov rax, 0
    push rax
    pop rax
    leave
    ret
.L6:
    mov rax, [rbp-24]
    push rax
    mov rax, [rbp-32]
    push rax
    pop rcx
    pop rax
    add rax, rcx
    push rax
    pop rax
    mov qword [rbp-24], rax
    jmp .L4
.L5:
    mov rax, 0
    push rax
    pop rax
    leave
    ret
    xor rax, rax
    leave
    ret
global lazyc_print_newline
lazyc_print_newline:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov byte  [rbp-1], 0
    lea rax, [rbp-1]
    push rax
    mov rax, 0
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 10
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-1]
    push rax
    mov rax, 0
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    pop rax
    push rax
    mov rax, 1
    push rax
    pop rsi
    pop rdi
    call lazyc_write_bytes
    push rax
    add rsp, 8
    mov rax, 0
    push rax
    pop rax
    leave
    ret
    xor rax, rax
    leave
    ret
global lazyc_print_char
lazyc_print_char:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov qword [rbp-8], rdi
    mov byte  [rbp-9], 0
    lea rax, [rbp-9]
    push rax
    mov rax, 0
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, [rbp-8]
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-9]
    push rax
    mov rax, 0
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    pop rax
    push rax
    mov rax, 1
    push rax
    pop rsi
    pop rdi
    call lazyc_write_bytes
    push rax
    add rsp, 8
    mov rax, 0
    push rax
    pop rax
    leave
    ret
    xor rax, rax
    leave
    ret
global lazyc_print_string
lazyc_print_string:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov qword [rbp-8], rdi
    mov rax, [rbp-8]
    push rax
    xor rax, rax
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    sete al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L7
    mov rax, 0
    push rax
    pop rax
    leave
    ret
.L7:
    mov rax, 0
    push rax
    pop rax
    mov qword [rbp-16], rax
.L8:
    mov rax, [rbp-8]
    push rax
    mov rax, [rbp-16]
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    pop rax
    movzx rax, byte [rax]
    push rax
    pop rax
    movzx rax, al
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    setne al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L9
    mov rax, [rbp-16]
    push rax
    mov rax, 1
    push rax
    pop rcx
    pop rax
    add rax, rcx
    push rax
    pop rax
    mov qword [rbp-16], rax
    jmp .L8
.L9:
    mov rax, [rbp-8]
    push rax
    mov rax, [rbp-16]
    push rax
    pop rsi
    pop rdi
    call lazyc_write_bytes
    push rax
    add rsp, 8
    mov rax, 0
    push rax
    pop rax
    leave
    ret
    xor rax, rax
    leave
    ret
global lazyc_print_long
lazyc_print_long:
    push rbp
    mov rbp, rsp
    sub rsp, 128
    mov qword [rbp-8], rdi
    mov rax, [rbp-8]
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    sete al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L10
    mov byte  [rbp-9], 0
    lea rax, [rbp-9]
    push rax
    mov rax, 0
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 48
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-9]
    push rax
    mov rax, 0
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    pop rax
    push rax
    mov rax, 1
    push rax
    pop rsi
    pop rdi
    call lazyc_write_bytes
    push rax
    add rsp, 8
    mov rax, 0
    push rax
    pop rax
    leave
    ret
.L10:
    mov rax, [rbp-8]
    push rax
    mov rax, -9223372036854775808
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    sete al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L11
    mov qword [rbp-29], 0
    mov qword [rbp-21], 0
    mov dword [rbp-13], 0
    lea rax, [rbp-29]
    push rax
    mov rax, 0
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 45
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 1
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 57
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 2
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 50
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 3
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 50
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 4
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 51
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 5
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 51
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 6
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 55
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 7
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 50
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 8
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 48
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 9
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 51
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 10
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 54
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 11
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 56
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 12
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 53
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 13
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 52
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 14
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 55
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 15
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 55
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 16
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 53
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 17
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 56
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 18
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 48
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 19
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 56
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    lea rax, [rbp-29]
    push rax
    mov rax, 0
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    pop rax
    push rax
    mov rax, 20
    push rax
    pop rsi
    pop rdi
    call lazyc_write_bytes
    push rax
    add rsp, 8
    mov rax, 0
    push rax
    pop rax
    leave
    ret
.L11:
    mov qword [rbp-53], 0
    mov qword [rbp-45], 0
    mov qword [rbp-37], 0
    mov rax, 0
    push rax
    pop rax
    mov qword [rbp-64], rax
    mov rax, 0
    push rax
    pop rax
    mov byte  [rbp-65], al
    mov rax, [rbp-8]
    push rax
    pop rax
    mov qword [rbp-80], rax
    mov rax, [rbp-80]
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    setl al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L12
    mov rax, 1
    push rax
    pop rax
    mov byte  [rbp-65], al
    mov rax, 0
    push rax
    mov rax, [rbp-80]
    push rax
    pop rcx
    pop rax
    sub rax, rcx
    push rax
    pop rax
    mov qword [rbp-80], rax
.L12:
.L13:
    mov rax, [rbp-80]
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    setg al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L14
    lea rax, [rbp-53]
    push rax
    mov rax, [rbp-64]
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 48
    push rax
    mov rax, [rbp-80]
    push rax
    mov rax, 10
    push rax
    pop rcx
    pop rax
    cqo
    idiv rcx
    mov rax, rdx
    push rax
    pop rcx
    pop rax
    add rax, rcx
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    mov rax, [rbp-64]
    push rax
    mov rax, 1
    push rax
    pop rcx
    pop rax
    add rax, rcx
    push rax
    pop rax
    mov qword [rbp-64], rax
    mov rax, [rbp-80]
    push rax
    mov rax, 10
    push rax
    pop rcx
    pop rax
    cqo
    idiv rcx
    push rax
    pop rax
    mov qword [rbp-80], rax
    jmp .L13
.L14:
    mov qword [rbp-112], 0
    mov qword [rbp-104], 0
    mov qword [rbp-96], 0
    mov qword [rbp-88], 0
    mov rax, 0
    push rax
    pop rax
    mov qword [rbp-120], rax
    movzx rax, byte [rbp-65]
    push rax
    pop rax
    cmp rax, 0
    je .L15
    lea rax, [rbp-112]
    push rax
    mov rax, [rbp-120]
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 45
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    mov rax, [rbp-120]
    push rax
    mov rax, 1
    push rax
    pop rcx
    pop rax
    add rax, rcx
    push rax
    pop rax
    mov qword [rbp-120], rax
.L15:
    mov rax, [rbp-64]
    push rax
    mov rax, 1
    push rax
    pop rcx
    pop rax
    sub rax, rcx
    push rax
    pop rax
    mov qword [rbp-128], rax
.L16:
    mov rax, [rbp-128]
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    setge al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L17
    lea rax, [rbp-112]
    push rax
    mov rax, [rbp-120]
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    lea rax, [rbp-53]
    push rax
    mov rax, [rbp-128]
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    pop rax
    movzx rax, byte [rax]
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    mov rax, [rbp-120]
    push rax
    mov rax, 1
    push rax
    pop rcx
    pop rax
    add rax, rcx
    push rax
    pop rax
    mov qword [rbp-120], rax
    mov rax, [rbp-128]
    push rax
    mov rax, 1
    push rax
    pop rcx
    pop rax
    sub rax, rcx
    push rax
    pop rax
    mov qword [rbp-128], rax
    jmp .L16
.L17:
    lea rax, [rbp-112]
    push rax
    mov rax, 0
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    pop rax
    push rax
    mov rax, [rbp-120]
    push rax
    pop rsi
    pop rdi
    call lazyc_write_bytes
    push rax
    add rsp, 8
    mov rax, 0
    push rax
    pop rax
    leave
    ret
    xor rax, rax
    leave
    ret
global lazyc_print_int16
lazyc_print_int16:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov qword [rbp-8], rdi
    mov rax, [rbp-8]
    push rax
    pop rdi
    call lazyc_print_long
    push rax
    pop rax
    leave
    ret
    xor rax, rax
    leave
    ret
global lazyc_readf
lazyc_readf:
    push rbp
    mov rbp, rsp
    sub rsp, 80
    mov qword [rbp-8], rdi
    mov rax, [rbp-8]
    push rax
    xor rax, rax
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    sete al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L18
    xor rax, rax
    push rax
    pop rax
    push rax
    pop rax
    leave
    ret
.L18:
    mov rax, 144
    push rax
    pop rdi
    call lazyc_alloc
    push rax
    pop rax
    mov qword [rbp-16], rax
    mov rax, [rbp-16]
    push rax
    xor rax, rax
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    sete al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L19
    xor rax, rax
    push rax
    pop rax
    push rax
    pop rax
    leave
    ret
.L19:
    mov rax, [rbp-8]
    push rax
    mov rax, [rbp-16]
    push rax
    pop rsi
    pop rdi
    call lazyc_sys_stat
    push rax
    pop rax
    mov qword [rbp-24], rax
    mov rax, [rbp-24]
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    setl al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L20
    mov rax, [rbp-16]
    push rax
    pop rdi
    call lazyc_free
    push rax
    add rsp, 8
    xor rax, rax
    push rax
    pop rax
    push rax
    pop rax
    leave
    ret
.L20:
    mov rax, [rbp-16]
    push rax
    mov rax, 48
    push rax
    pop rcx
    pop rax
    add rax, rcx
    push rax
    pop rax
    push rax
    pop rax
    mov qword [rbp-32], rax
    mov rax, [rbp-32]
    push rax
    pop rax
    mov rax, [rax]
    push rax
    pop rax
    mov qword [rbp-40], rax
    mov rax, [rbp-16]
    push rax
    pop rdi
    call lazyc_free
    push rax
    add rsp, 8
    mov rax, [rbp-40]
    push rax
    mov rax, 1
    push rax
    pop rcx
    pop rax
    add rax, rcx
    push rax
    pop rdi
    call lazyc_alloc
    push rax
    pop rax
    mov qword [rbp-48], rax
    mov rax, [rbp-48]
    push rax
    xor rax, rax
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    sete al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L21
    xor rax, rax
    push rax
    pop rax
    push rax
    pop rax
    leave
    ret
.L21:
    mov rax, [rbp-8]
    push rax
    mov rax, 0
    push rax
    mov rax, 0
    push rax
    pop rdx
    pop rsi
    pop rdi
    call lazyc_sys_open
    push rax
    pop rax
    mov qword [rbp-56], rax
    mov rax, [rbp-56]
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    setl al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L22
    mov rax, [rbp-48]
    push rax
    pop rdi
    call lazyc_free
    push rax
    add rsp, 8
    xor rax, rax
    push rax
    pop rax
    push rax
    pop rax
    leave
    ret
.L22:
    mov rax, 0
    push rax
    pop rax
    mov qword [rbp-64], rax
.L23:
    mov rax, [rbp-64]
    push rax
    mov rax, [rbp-40]
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    setl al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L24
    mov rax, [rbp-56]
    push rax
    mov rax, [rbp-48]
    push rax
    mov rax, [rbp-64]
    push rax
    pop rcx
    pop rax
    add rax, rcx
    push rax
    mov rax, [rbp-40]
    push rax
    mov rax, [rbp-64]
    push rax
    pop rcx
    pop rax
    sub rax, rcx
    push rax
    pop rdx
    pop rsi
    pop rdi
    call lazyc_sys_read
    push rax
    pop rax
    mov qword [rbp-72], rax
    mov rax, [rbp-72]
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    setl al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L25
    mov rax, [rbp-56]
    push rax
    pop rdi
    call lazyc_sys_close
    push rax
    add rsp, 8
    mov rax, [rbp-48]
    push rax
    pop rdi
    call lazyc_free
    push rax
    add rsp, 8
    xor rax, rax
    push rax
    pop rax
    push rax
    pop rax
    leave
    ret
.L25:
    mov rax, [rbp-72]
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    sete al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L26
    jmp .L24
.L26:
    mov rax, [rbp-64]
    push rax
    mov rax, [rbp-72]
    push rax
    pop rcx
    pop rax
    add rax, rcx
    push rax
    pop rax
    mov qword [rbp-64], rax
    jmp .L23
.L24:
    mov rax, [rbp-56]
    push rax
    pop rdi
    call lazyc_sys_close
    push rax
    add rsp, 8
    mov rax, [rbp-48]
    push rax
    mov rax, [rbp-64]
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    mov rax, 0
    push rax
    pop rax
    movzx rax, al
    push rax
    pop rax
    pop rcx
    mov byte  [rcx], al
    mov rax, [rbp-48]
    push rax
    pop rax
    leave
    ret
    xor rax, rax
    leave
    ret
global lazyc_writef
lazyc_writef:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov qword [rbp-8], rdi
    mov qword [rbp-16], rsi
    mov rax, [rbp-8]
    push rax
    xor rax, rax
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    sete al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L27
    mov rax, 0
    push rax
    pop rax
    leave
    ret
.L27:
    mov rax, [rbp-16]
    push rax
    xor rax, rax
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    sete al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L28
    mov rax, 0
    push rax
    pop rax
    leave
    ret
.L28:
    mov rax, [rbp-8]
    push rax
    mov rax, 577
    push rax
    mov rax, 420
    push rax
    pop rdx
    pop rsi
    pop rdi
    call lazyc_sys_open
    push rax
    pop rax
    mov qword [rbp-24], rax
    mov rax, [rbp-24]
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    setl al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L29
    mov rax, 0
    push rax
    pop rax
    leave
    ret
.L29:
    mov rax, 0
    push rax
    pop rax
    mov qword [rbp-32], rax
.L30:
    mov rax, [rbp-16]
    push rax
    mov rax, [rbp-32]
    push rax
    pop rax
    pop rcx
    add rax, rcx
    push rax
    pop rax
    movzx rax, byte [rax]
    push rax
    pop rax
    movzx rax, al
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    setne al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L31
    mov rax, [rbp-32]
    push rax
    mov rax, 1
    push rax
    pop rcx
    pop rax
    add rax, rcx
    push rax
    pop rax
    mov qword [rbp-32], rax
    jmp .L30
.L31:
    mov rax, 0
    push rax
    pop rax
    mov qword [rbp-40], rax
.L32:
    mov rax, [rbp-40]
    push rax
    mov rax, [rbp-32]
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    setl al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L33
    mov rax, [rbp-24]
    push rax
    mov rax, [rbp-16]
    push rax
    mov rax, [rbp-40]
    push rax
    pop rcx
    pop rax
    add rax, rcx
    push rax
    mov rax, [rbp-32]
    push rax
    mov rax, [rbp-40]
    push rax
    pop rcx
    pop rax
    sub rax, rcx
    push rax
    pop rdx
    pop rsi
    pop rdi
    call lazyc_sys_write
    push rax
    pop rax
    mov qword [rbp-48], rax
    mov rax, [rbp-48]
    push rax
    mov rax, 0
    push rax
    pop rcx
    pop rax
    cmp rax, rcx
    setle al
    movzx rax, al
    push rax
    pop rax
    cmp rax, 0
    je .L34
    mov rax, [rbp-24]
    push rax
    pop rdi
    call lazyc_sys_close
    push rax
    add rsp, 8
    mov rax, 0
    push rax
    pop rax
    leave
    ret
.L34:
    mov rax, [rbp-40]
    push rax
    mov rax, [rbp-48]
    push rax
    pop rcx
    pop rax
    add rax, rcx
    push rax
    pop rax
    mov qword [rbp-40], rax
    jmp .L32
.L33:
    mov rax, [rbp-24]
    push rax
    pop rdi
    call lazyc_sys_close
    push rax
    add rsp, 8
    mov rax, 1
    push rax
    pop rax
    leave
    ret
    xor rax, rax
    leave
    ret
